import os
from dotenv import load_dotenv

load_dotenv()

class Settings:
    TELEGRAM_ENABLED = os.getenv("TELEGRAM_ENABLED", "false").lower() == "true"
    TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
    TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
    ROBOT_NAME = os.getenv("ROBOT_NAME", "robot")

settings = Settings()


# TEST MODE
MODE = "SIMULATION"
#MODE = "SAFE"
# MODE = "PRODUCTION"
#===================

# SERVO
PAN_MIN = 40
PAN_MAX = 140
TILT_MIN = 70
TILT_MAX = 110
PAN_DEFAULT = 90
TILT_DEFAULT = 90
#=====================


# CAMERA
FRAME_HEIGHT = 640
FRAME_WIDTH = 480
#====================


# MOTOR
LOW_SPEED = 5
MEDIUM_SPEED = 10
HIGH_SPEED = 15

TURN_SPEED = 15
FORWARD_SPEED = 15
BACKWARD_SPEED = 15
STOP_SPEED = 0
#====================


# SCAN
SCAN_PAN_STEP = 2
SCAN_TILT_STEP = 4
SCAN_DIRECTION = 1
DELAY = 0.5
#=======================


# TRACKING
TRACKING_PAN_STEP = 2
TRACKING_TILT_STEP = 2
CENTER_TOLERANCE_X = 20
CENTER_TOLERANCE_Y = 20
MOVE_TOLERANCE_X = 40
MOVE_TOLERANCE_Y = 30
MIN_TARGET_AREA = 500
TARGET_AREA_FAR = 2500
TARGET_AREA_MEDIUM = 8000
TARGET_AREA_NEAR =18000
